# Generated by Django 5.0.4 on 2024-06-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('videoId', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('problemStatement', models.TextField()),
                ('constraints', models.TextField()),
                ('handlerFunction', models.CharField(max_length=200)),
                ('starterCode', models.TextField()),
                ('starterFunctionName', models.CharField(max_length=100)),
            ],
        ),
    ]
