# Generated by Django 5.0.4 on 2024-06-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='handlerFunction',
            field=models.TextField(),
        ),
    ]
