# Generated by Django 5.0.4 on 2024-06-23 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inputText', models.TextField()),
                ('outputText', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('img', models.URLField(blank=True, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='problem.problem')),
            ],
        ),
    ]
